# Generated by Django 3.2.9 on 2021-11-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidusermodel',
            name='image',
            field=models.ImageField(default=1, upload_to='to_predict'),
            preserve_default=False,
        ),
    ]
