# Generated by Django 3.2.9 on 2021-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_covidusermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidusermodel',
            name='image',
            field=models.FileField(upload_to='to_predict'),
        ),
    ]
