# Generated by Django 3.2.9 on 2021-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_covidusermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidusermodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidusermodel',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
